### ISSUE TITLE
Dexed crashes if disconnect all in carla and reattaching audio output

### ISSUE THREAD

**Issue by muziker** [asb2m10/dexed#260]
In v0.9.5-9-g7026151, under linux, if all the audio outputs are disconnected, then reconnected, dexed crashes. To solve, always have the audio outputs connected before disconnecting extraneous outputs

**Comment by asb2m10** [comment]
Can you test this with the latest version to see if this is resolved ?

**Comment by akwizgran** [comment]
This still happens in 0.9.6. I'm using QjackCtl rather than Carla, but the issue is the same: if all audio outputs are disconnected and then a new audio output is connected, Dexed crashes. If the new output is connected before disconnecting the old ones, there's no crash.

Here's a backtrace from gdb:

```
Thread 6 "Dexed" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff590c6c0 (LWP 424533)]
0x00005555554a6fd5 in juce::FloatVectorOperations::copy(float*, float const*, int) ()
(gdb) bt
#0  0x00005555554a6fd5 in juce::FloatVectorOperations::copy(float*, float const*, int) ()
#1  0x000055555549c42d in DexedAudioProcessor::processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) ()
#2  0x00005555555160fb in juce::AudioProcessorPlayer::audioDeviceIOCallback(float const**, int, float**, int, int) ()
#3  0x00005555554c3572 in juce::AudioDeviceManager::audioDeviceIOCallbackInt(float const**, int, float**, int, int) ()
#4  0x00005555554ca4b6 in juce::JackAudioIODevice::process(int) ()
#5  0x00005555554ca527 in juce::JackAudioIODevice::processCallback(unsigned int, void*) ()
#6  0x00007ffff5d5cb5d in ?? () from /lib/x86_64-linux-gnu/libjack.so.0
#7  0x00007ffff5d5c828 in ?? () from /lib/x86_64-linux-gnu/libjack.so.0
#8  0x00007ffff5d7906c in ?? () from /lib/x86_64-linux-gnu/libjack.so.0
#9  0x00007ffff78a81c4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#10 0x00007ffff792885c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by akwizgran** [comment]
Sorry, I've just noticed that I'm two releases behind. This is fixed in 0.9.8 :tada:
